[project]
name = "mmt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matthew Shun-Shin", email = "m@shun-shin.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.3",
    "scikit-image>=0.24.0",
    "scikit-learn>=1.5.2",
    "scipy>=1.14.1",
]

[project.scripts]
mmt = "mmt:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
